<?php

namespace App\Models\Machine;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class EMPAll extends Model
{
    use HasFactory;

    const CREATED_AT = 'CREATE_TIME';
    const UPDATED_AT = 'MODIFY_TIME';

    public $incrementing = false;
    public $timestamps = false;
    protected $primaryKey = "EMP_CODE";
    protected $keyType = 'string';
    public $table ='EMCS_EMPLOYEE';

    protected $fillable = ['EMP_CODE','EMP_CARD_NO','EMP_CARD_SCAN','EMP_PAYROLL','EMP_GROUP','EMP_TYPE','EMP_MODE','EMP_DIRECT','EMP_TAXTYPE'
    ,'EMP_ICON','EMP_EN_TITLE_CODE','EMP_EN_NAME_TITLE','EMP_EN_NAME_FIRST','EMP_EN_NAME_LAST','EMP_EN_NICKNAME','EMP_TH_TITLE_CODE'
    ,'EMP_TH_NAME_TITLE','EMP_TH_NAME_FIRST','EMP_TH_NAME_MIDDLE','EMP_TH_NAME_LAST','EMP_TH_NICKNAME','EMP_NEW_SALARY'
    ,'EMP_NEW_COSTOFLIVING','EMP_NEW_POSITION','EMP_INCOME_BASE','EMP_INCOME_CALC','EMP_INCOME_DAY','EMP_RATE_OT10'
    ,'EMP_RATE_OT15','EMP_RATE_OT20','EMP_RATE_OT30','EMP_OLD_SALARY','EMP_OLD_COSTOFLIVING','EMP_OLD_POSITION','EMP_END_SALARY'
    ,'EMP_PAY_TYPE','EMP_USERNAME','EMP_YEAR','EMP_MONTH','EMP_SALARY','EMP_INFORMATION','EMP_BIRTHDAY','EMP_AGE','EMP_SEX','EMP_NATION'
    ,'EMP_MARTIAL','EMP_CHILD_M','EMP_CHILD_F','EMP_FATHER','EMP_MOTHER','EMP_ID_NUMBER','EMP_ISSUED_AT','EMP_DATE_ISSUE','EMP_DATE_EXPIRE'
    ,'EMP_ID_TAX','EMP_ID_SSO','EMP_ID_BANK','EMP_BRANCH','EMP_BANK','EMP_CHILD_EDUCATION','EMP_TALENT','EMP_P_ADDR','EMP_P_MU','EMP_P_ALLEY'
    ,'EMP_P_ROAD','EMP_P_TAMBOL','EMP_P_AMPHUR','EMP_P_PROVINCE','EMP_P_POSTCODE','EMP_P_PHONE_HOME','EMP_P_PHONE_WORK','EMP_P_PHONE_MOBILE'
    ,'EMP_P_PAGER','EMP_P_REFERENCE','EMP_P_REF_ADD','EMP_P_REF_PHONE','EMP_P_EMERGENT','EMP_P_EME_ADD','EMP_P_EME_PHONE','EMP_VAT_METHOD'
    ,'EMP_VAT_METHOD91','EMP_VAT_EXPENSE','EMP_VAT_INTEREST_HOME','EMP_VAT_INSURANCE','EMP_VAT_DONATE','EMP_VAT_PARENT1','EMP_VAT_PARENT2'
    ,'EMP_VAT_CHILD1','EMP_VAT_CHILD2','EMP_VAT_LIVE','EMP_VAT_SSO','EMP_VAT_RMF','EMP_VAT_LTF','EMP_VAT_DONATE_EDUCATION','EMP_VAT_RATE'
    ,'EMP_NET_INCOME','EMP_NET_REDUCT','EMP_NET_BEFORE_TAX','EMP_NET_TAX','EMP_NET_TAX_CALC','EMP_WORK_STARTDATE','EMP_WORK_ENDDATE'
    ,'EMP_WORK_YEAR','EMP_WORK_MONTH','EMP_WORK_DAY','EMP_INSURANCE','EMP_SIGN','EMP_TRAIN','EMP_STATUS','EMP_SSO','EMP_POSTED','COUNTRY_CODE'
    ,'COMPANY_CODE','WAREHOUSE_CODE','DEPART_CODE','DIVISION_CODE','SECTION_CODE','SHIFT_CODE','LINE_CODE','TODAY_YY','TODAY_MAX','CREATE_BY','CREATE_TIME'
    ,'MODIFY_BY','MODIFY_TIME','UNID','PM_EMP_STATUS','EMP_STAFF','EMP_WORK_PRODATE','EMP_PRO_DATE060','EMP_PRO_DATE090','EMP_PRO_DATE120','EMP_PRO_PASS060'
    ,'EMP_PRO_PASS090','EMP_PRO_PASS120','EMP_PRO_REF060','EMP_PRO_REF090','EMP_PRO_REF120','POSITION_CODE','DV_STARTDATE','DV_ENDDATE','DV_INSTITUTION_CODE'
    ,'EMP_VISA_NO','EMP_VISA_EXPIRE','EMP_VISA_COST','WORKPERMIT_NO','WORKPERMIT_EXP','WORKPERMIT_COST','PASSPORT_NO','PASSPORT_EXP','PASSPORT_COST'
    ,'PINKCARD_NO','PINKCARD_EXP','PINKCARD_COST','EMP_NEW_OPTION1','EMP_NEW_OPTION2','EMP_FATHER_CARD','EMP_MOTHER_CARD','EMP_FATHER_STATUS'
    ,'EMP_MOTHER_STATUS','EMP_SPOUSE','EMP_YOUNG_CARD1','EMP_YOUNG_CARD2','EMP_FATHER_NAME','EMP_MOTHER_NAME','EMP_YOUNG_NAME1','EMP_YOUNG_NAME2'
    ,'EMP_SPOUSE_CARD','EMP_SPOUSE_STATUS','EMP_COST_TYPE','SP_1','SP_2','SP_3','SP_4','SP_5','SP_6','SP_7','INSURER_TYPE','TR_CODE','EMP_VAT_1'
    ,'EMP_VAT_2','EMP_VAT_3','EMP_VAT_4','EMP_NEW_OPTION3','EMP_PAYROLL_STATUS','EMP_NEW_OPTION4','EMP_HOSPITAL_NO1','EMP_HOSPITAL_NO2','EMP_SON_TYPE'
    ,'EMP_SON_TOTAL','EMP_YEAR_BIRTH1','EMP_YEAR_BIRTH2','EMP_AGE_SON1','EMP_AGE_SON2','EMP_ADDRESS','EMP_SSO_PERIOD_IN','EMP_SSO_PERIOD_OUT'
    ,'EMP_DV_EDUCATION','EMP_DV_INTERNSHIP','DIVISION_CODE_NAME','SECTION_CODE_NAME'];
}
